apiVersion: apps/v1
kind: Deployment
metadata:
  name: CityNexus.People
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CityNexus.People
  template:
    metadata:
      labels:
        app: CityNexus.People
    spec:
      containers:
        - name: CityNexus.People
          image: ismael3s/citynexus.people:99cc1dd
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
